dist: xenial

services:
  - docker

install: true

before_script:
  - export API_SESSION_COOKIE_SECRET_KEY=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
  - cp .env.sample .env
  - docker-compose up -d postgres redis
  - docker-compose build api
  - docker-compose run migrations

script:
  - docker-compose run api pytest --cov --cov-config=.coveragerc --cov-report xml

after_script:
  - docker-compose down -v

after_success:
  - coveralls debug

branches:
  only:
  - master
