"""add bookmarks table

Revision ID: 1f74339f95ba
Revises: 0ee140bf938a
Create Date: 2019-07-05 23:10:26.409742

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1f74339f95ba'
down_revision = '0ee140bf938a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('song_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
